sudo: required
services:
 - docker

before_install:
  
  - docker build -t aollaku/client-test -f ./client/Dockerfile.dev ./client

script:
# -e CI=TRUE is to run the test all the time without exit.
 - docker run -e CI=true aollaku/client-test npm test

after_success:

 - docker build -t aollaku/andi-multi-client ./client
 - docker build -t aollaku/andi-multi-server ./server
 - docker build -t aollaku/andi-multi-nginx ./nginx
 - docker build -t aollaku/andi-multi-worker ./worker

 # Login to the docker.

 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
 # push the build to docker hub
 
 - docker push aollaku/andi-multi-client
 - docker push aollaku/andi-multi-server
 - docker push aollaku/andi-multi-nginx
 - docker push aollaku/andi-multi-worker

  # Create access key and secret access key for AWS on Travis CI variables and add those variables here.

