sudo: required
services:
 - docker

before_install:
  
  - docker build -t aollaku/client-test -f ./client/Dockerfile.dev ./client

script:

 - docker run -e CI=true aollaku/client test npm test

after_success:

 - docker build -t aollaku/client ./client
 - docker build -t aollaku/server ./server
 - docker build -t aollaku/nginx ./nginx
 - docker build -t aollaku/worker ./worker


  