version: '3'
services:

 postgres:
  image: 'postgres:latest'

 redis:
  image: redis:latest

 api:
  build:
   dockerfile: Dockerfile.dev
   context: ./server
  volumes:
   - /opt/app/node_modules
   - ./server:/opt/app

  environment:
   - REDIS_HOST=redis
   - REDIS_PORT=6379
   - PGUSER=postgres
   - PGHOST=postgres
   - PGDATABASE=postgres
   - PGPASSWORD=postgres_password
   - PGPORT=5432
 
 client:
  build:
   dockerfile: Dockerfile.dev
   context: ./client
  volumes:
   - /opt/app/node_modules
   - ./client:/opt/app
 
 worker:
  build:
   dockerfile: Dockerfile.dev
   context: ./worker
  volumes:
   - /opt/app/node_modules
   - ./worker:/opt/app
 
 nginx:
  restart: always
  build:
   dockerfile: Dockerfile.dev
   context: ./nginx
  ports:
   - 3050:80
  
